name = "TestTests"
uuid = "a2249cae-1078-4a6b-8c9d-855fbe328692"
authors = ["Leandro Martinez <leandro@iqm.unicamp.br> and contributors"]
version = "0.1.0"

[deps]

[compat]
julia = "1"

[extras]
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["TestItemRunner"]
